version: '3'
services:
    coleira-qr-code:
      build: 
          context: .
          dockerfile: Dockerfile
      container_name: coleira-qr-code
      ports:
          - "510:80"
      volumes:
          - .:/usr/src/app/
      environment:
          - APPLICATION_ENV=development