version: '3'
services:
    comanda-eletronica-node:
      build: 
          context: .
          dockerfile: Dockerfile
      container_name: comanda-eletronica-node
      ports:
          - "510:80"
      volumes:
          - .:/usr/src/app/
      environment:
          - APPLICATION_ENV=development