version: '3'
services:
    comanda_eletronica_front:
      build: 
          context: .
          dockerfile: Dockerfile
      container_name: comanda_eletronica_front
      ports:
          - "8085:80"
      volumes:
          - .:/var/www/
          #- ./server/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      environment:
          - APPLICATION_ENV=development